### ISSUE TITLE
BUG! *readme needs a link to the website* BUG!

### ISSUE THREAD

**Issue by fairclothjm** [andrewkeithly/andrewkeithly.github.io#1]
Come on, we aren't savages.

**Comment by andrewkeithly** [comment]
LOL just saw this...

would be so useful too as I can't remember how to get there myself...

**Comment by andrewkeithly** [comment]
[Consider it closed. ](https://github.com/andrewkeithly/andrewkeithly.github.io/commit/3a68a964d8212bbb7b1e256f3d2b94727c486db6)

**Comment by fairclothjm** [comment]
I figured you just decided this was a `wontfix` 

:)
